/* Board Sense Spike Glass dual-photo mode v0.3 */
(function(){
'use strict';
const TARGET_KEY='scrapRadarInspectionTargetV1';
function E(id){return document.getElementById(id)}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function readTarget(){try{return JSON.parse(localStorage.getItem(TARGET_KEY)||'null')}catch(_){return null}}

/* Override the older broad "ic" substring test in the page renderer.
   This prevents magnetIC from being described as an IC/logic package. */
window.blueprintTip=function(label){
 var l=String(label||'').toLowerCase();
 if(l.indexOf('gold finger')>=0||l.indexOf('edge contact')>=0)return'High-interest contact area. Keep segregated when practical and confirm plating before assigning value.';
 if(l.indexOf('plated contact')>=0||l.indexOf('keypad')>=0)return'Flat contact surface, not a capacitor. Useful for board identification; plating may be thin flash over base metal.';
 if(l.indexOf('copper-wound magnetic')>=0||l.indexOf('magnetic candidate')>=0||l.indexOf('voice coil')>=0)return'Magnetic or voice-coil candidate. Inspect for accessible copper winding, steel or ferrite structure, and keep magnet chemistry unproven until separately identified.';
 if(l.indexOf('ic /')>=0||l.indexOf('ic-like')>=0||l.indexOf('logic package')>=0)return'Logic package. Markings, package style and board function matter more than dark color alone.';
 if(l.indexOf('transformer')>=0||l.indexOf('relay')>=0||l.indexOf('power block')>=0)return'Power-section hardware. Inspect for copper windings, relay contacts, steel cores and removable heat sinks.';
 if(l.indexOf('capacitor')>=0)return'Power component candidate. Treat as a family-level visual match until shape and board context agree.';
 return'Board Sense marked this as a useful inspection point. Confirm the part before assigning recovery value.';
};

function injectStyle(){if(E('spikeDualStyle'))return;var s=document.createElement('style');s.id='spikeDualStyle';s.textContent='.spike-dual-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin:10px 0}.spike-photo-slot{padding:12px;border:1px solid rgba(180,76,255,.55);border-radius:12px;background:#0d0911}.spike-photo-slot b{display:block;color:#d8b7ff;margin-bottom:4px}.spike-photo-slot small{display:block;color:#aaa;line-height:1.35}.spike-pair-summary{padding:12px;border:1px solid #00d4ff;border-radius:12px;background:#07131a;margin:10px 0;color:#dff8ff}.spike-pair-view{padding:8px 0;border-top:1px solid rgba(255,255,255,.1)}.spike-pair-view:first-of-type{border-top:0}.spike-selected{color:#8dff7a;font-weight:700}@media(max-width:700px){.spike-dual-grid{grid-template-columns:1fr}}';document.head.appendChild(s)}
function pairSummary(data){var rows=data&&data.pair_summary||[];var selected=data&&data.selected_role||'context';var h='<div class="spike-pair-summary"><b>📸📸 SPIKE two-photo cross-check</b><p class="muted">Photo 1 supplies location/context. Photo 2 can supply the tighter component evidence.</p>';rows.forEach(function(r){var role=r.role==='closeup'?'Photo 2 • Close-up':'Photo 1 • Context';var sel=r.role===selected?' <span class="spike-selected">✓ selected evidence</span>':'';h+='<div class="spike-pair-view"><b>'+role+'</b>'+sel+'<br>Generic: '+esc(r.generic_label||'no strong match')+(r.generic_confidence!=null?' • '+esc(r.generic_confidence)+'%':'')+(r.target_status?'<br>Target state: '+esc(String(r.target_status).replace(/_/g,' ')):'')+(r.target_confidence!=null?'<br>Target geometry: '+esc(r.target_confidence)+'%':'')+'</div>'});return h+'<small>'+esc(data&&data.integrity_rule||'The two views guide one inspection mission; they do not manufacture composition or value.')+'</small></div>'}
async function analyzeDual(){var contextInput=E('spikeImage'),closeInput=E('spikeImageCloseup'),status=E('spikeStatus'),box=E('spikeBox');var first=contextInput&&contextInput.files&&contextInput.files[0],second=closeInput&&closeInput.files&&closeInput.files[0];if(!first&&!second){if(status)status.textContent='Choose a context photo or close-up first.';return}if(!first&&second){first=second;second=null}var btn=E('spikeBtn');if(btn)btn.disabled=true;if(status)status.textContent=second?'SPIKE is cross-checking both photos...':'SPIKE is analyzing one photo...';try{var form=new FormData();form.append('context',first);if(second)form.append('closeup',second);var target=readTarget();if(target&&target.target)form.append('inspection_target',JSON.stringify(target));var api=window.API||'https://boardsense.scrapradarfamily.com';var response=await fetch(api+'/analyze-spike-pair',{method:'POST',body:form});var data=await response.json();if(!response.ok)throw new Error(data&&data.message||('HTTP '+response.status));var combined=data.combined||(data.views&&data.views[0]);if(!combined)throw new Error('SPIKE returned no analysis view.');var rendered=typeof window.renderSpike==='function'?window.renderSpike(combined):'<div class="warning-box">SPIKE result renderer unavailable.</div>';if(box)box.innerHTML=pairSummary(data)+rendered;if(E('blueprintBox')&&typeof window.renderBlueprint==='function')E('blueprintBox').innerHTML=window.renderBlueprint(combined);if(target&&target.target){var lab=E('labBox');if(lab)lab.innerHTML='<div class="warning-box"><b>🎯 Target mission active: generic recovery routing withheld.</b><br>SPIKE is comparing context and close-up views for <b>'+esc(target.target)+'</b>.</div>'}else if(E('labBox')&&typeof window.renderLabs==='function'){E('labBox').innerHTML=window.renderLabs(combined)}if(typeof window.loadMarket==='function')window.loadMarket();if(status)status.textContent=(data.photo_count===2?'Two-photo':'Single-photo')+' Spike Glass recognition complete.'}catch(e){if(status)status.textContent='Analysis failed: '+e.message}finally{if(btn)btn.disabled=false}}
function install(){if(window.__spikeDualInstalled)return true;var first=E('spikeImage'),oldBtn=E('spikeBtn');if(!first||!oldBtn)return false;window.__spikeDualInstalled=true;injectStyle();var grid=document.createElement('div');grid.className='spike-dual-grid';grid.id='spikeDualGrid';var slot1=document.createElement('div');slot1.className='spike-photo-slot';slot1.innerHTML='<b>Photo 1 • Context</b><small>Show enough of the item to locate the target.</small>';first.parentNode.insertBefore(grid,first);grid.appendChild(slot1);slot1.appendChild(first);var slot2=document.createElement('div');slot2.className='spike-photo-slot';slot2.innerHTML='<b>Photo 2 • Close-up (optional)</b><small>Move closer to the exact component or feature SPIKE is checking.</small><input type="file" id="spikeImageCloseup" accept="image/*">';grid.appendChild(slot2);var btn=oldBtn.cloneNode(true);btn.textContent='Open Spike Glass • 1–2 Photos';oldBtn.parentNode.replaceChild(btn,oldBtn);btn.addEventListener('click',analyzeDual);var status=E('spikeStatus');if(status&&status.textContent==='Recognition mode ready.')status.textContent='Ready. Use one photo, or add a second close-up for a stronger cross-check.';return true}
var tries=0;(function wait(){tries++;if(install()||tries>100)return;setTimeout(wait,100)})();
})();
