/* Printable Board Sense + Scrap Radar case sheet. A market benchmark is never a yield. */
(function(){
'use strict';
var KEY='scrapRadarYardQuotesV1',GRAMS_PER_LB=453.59237,active=null,market=null;
function E(id){return document.getElementById(id)}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function cash(v){return '$'+Number(v).toFixed(2)}
function number(v){var n=Number(v);return v!==''&&v!=null&&isFinite(n)&&n>=0?n:null}
function gradeId(grade,type){if(/cell\s*phone|smart\s*phone|\bGSM\b|\bLTE\b/i.test(String(type||'')))return 'cell_phone_boards';var s=String(grade||'').toUpperCase();return s==='HIGH'?'board_high':s==='LOW'?'board_low':s==='MEDIUM'||s==='MID'?'board_mid':null}
function buyerReference(id){return window.ScrapRadarBoardPriceReference&&window.ScrapRadarBoardPriceReference.get(id)}
var CATEGORIES=[['cell_phone_boards','Clean cell phone boards'],['board_high','High grade circuit boards'],['board_mid','Mid grade circuit boards'],['board_low','Low grade circuit boards']];
function quoteFor(id){try{var q=JSON.parse(localStorage.getItem(KEY)||'{}'),n=number(q[id]);return n}catch(_){return null}}
function priceNote(id){var q=quoteFor(id),r=buyerReference(id);if(q!=null)return 'Saved local buyer quote on this device. Confirm it is still current.';if(!r)return 'No board planning price available; enter a buyer quote. Metal spot prices are not board payouts.';return 'U.S. buyer-sample planning estimate dated '+esc(r.date)+(r.stale?' • reference is over 30 days old':'')+'. Sample rates: '+r.samples.map(function(x){return '<a href="'+esc(x.url)+'" target="_blank" rel="noopener">'+esc(x.buyer)+' '+cash(x.price)+'/lb</a>'}).join(' and ')+'. Not a nationwide survey or guaranteed payout.'}
function refreshCategory(){var id=E('case-category').value,q=quoteFor(id),r=buyerReference(id),input=E('case-price');input.value=q!=null?q:r?r.price:'';input.dataset.edited='no';input.dataset.origin=q!=null?'saved local buyer quote':r?'dated U.S. buyer-sample planning estimate':'entered price';E('case-price-label').textContent='Planning price for '+(CATEGORIES.find(function(x){return x[0]===id})||['','selected board'])[1]+' ($/lb)';E('case-price-note').innerHTML=priceNote(id);refreshTotals()}
function sourceBlueprint(p){var d=p.combined||{},b=d.board_blueprint||{};if(b.available&&b.image_url)return b;var views=p.views||[];for(var i=0;i<views.length;i++){b=views[i]&&views[i].board_blueprint||{};if(b.available&&b.image_url)return b}return null}
function photoViews(p){var views=(p.views||[]).map(function(v,i){return {label:'Photo '+(v.view_number||i+1),blueprint:v.board_blueprint||{}}}).filter(function(v){return v.blueprint.available&&v.blueprint.image_url});if(views.length)return views.slice(0,2);var b=sourceBlueprint(p);return b?[{label:'Selected board view',blueprint:b}]:[]}
function style(){if(E('boardCaseReportStyle'))return;var s=document.createElement('style');s.id='boardCaseReportStyle';s.textContent=`
#boardCaseReport{background:#080b07;color:#f2f5e9;border:2px solid #bfe82a;border-radius:18px;padding:18px;margin:18px 0;box-shadow:0 0 22px #bbf52325}
#boardCaseReport *{box-sizing:border-box}#boardCaseReport h2{color:#d6ff00;margin:0 0 6px}#boardCaseReport h3{color:#d6ff00;margin:12px 0 8px}
#boardCaseReport .case-head{display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap;border-bottom:1px solid #637319;padding-bottom:12px}
#boardCaseReport .case-kicker{color:#d6ff00;font-size:.82rem;letter-spacing:.14em;font-weight:bold}#boardCaseReport .case-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:12px;margin:14px 0}
#boardCaseReport .case-card{background:#10150c;border:1px solid #687b27;border-radius:11px;padding:12px;line-height:1.5}#boardCaseReport .case-card b{color:#e4ff72}
#boardCaseReport .case-photo{width:100%;max-height:850px;object-fit:contain;background:#000;border:1px solid #bfe82a;border-radius:9px}
#boardCaseReport .case-index{display:grid;grid-template-columns:repeat(auto-fit,minmax(205px,1fr));gap:8px}#boardCaseReport .case-index-item{background:#141914;border:1px solid #475525;border-radius:9px;padding:9px}
#boardCaseReport .case-number{display:inline-flex;align-items:center;justify-content:center;border-radius:50%;background:#d6ff00;color:#090909;width:26px;height:26px;margin-right:7px;font-weight:bold}
#boardCaseReport .case-note{color:#c2c8b4;font-size:.89rem}#boardCaseReport label{display:block;color:#d6ff00;font-weight:600}#boardCaseReport input,#boardCaseReport select{width:100%;padding:9px;margin:5px 0;color:white;background:#0b0f0b;border:1px solid #829a36;border-radius:7px;font-size:1rem}
#boardCaseReport button{padding:9px 12px;border:1px solid #d6ff00;background:#141a10;color:#d6ff00;border-radius:8px;cursor:pointer}#boardCaseReport .case-total{font-size:1.35rem;color:#e7ff98;font-weight:bold}
@media print{body *{visibility:hidden!important}#boardCaseReport,#boardCaseReport *{visibility:visible!important}#boardCaseReport{position:absolute;left:0;top:0;width:100%;color:#111;background:white;border:0;box-shadow:none}#boardCaseReport .case-card,#boardCaseReport .case-index-item{background:white;color:#111;border-color:#777}#boardCaseReport h2,#boardCaseReport h3,#boardCaseReport b,#boardCaseReport label,#boardCaseReport .case-kicker{color:#111!important}#boardCaseReport button{display:none}#boardCaseReport .case-photo{max-height:500px}#boardCaseReport .case-note{color:#333}}
`;document.head.appendChild(s)}
function ensure(){var box=E('boardCaseReport');if(box)return box;var anchor=E('blueprintBox');if(!anchor)return null;style();box=document.createElement('section');box.id='boardCaseReport';box.setAttribute('aria-live','polite');anchor.closest('section').insertAdjacentElement('afterend',box);box.hidden=true;return box}
function marketHTML(d){var m=market||{},metals=m.metals||{},rows=[['gold','Gold'],['silver','Silver'],['platinum','Platinum'],['palladium','Palladium'],['iridium','Iridium']];return '<div class="case-grid">'+rows.map(function(row){var x=metals[row[0]]||{},ok=x.available&&number(x.price)>0;return '<div class="case-card"><b>'+row[1]+'</b><br>'+(ok?cash(x.price)+' / '+esc(x.unit||'unit'):'Market price unavailable')+'<br><span class="case-note">'+(ok?'Price date: '+esc(x.source_price_date||'unverified')+(x.stale?' • stale':''):'')+' • Recoverable quantity unmeasured</span></div>'}).join('')+'</div><p class="case-note">Scrap Radar market references are metal prices, not the amount in this board or a refiner payout. A yield or assay is required for metal-specific recovery dollars.</p>'}
function refreshTotals(){if(!active)return;var weight=number(E('case-weight').value),price=number(E('case-price').value),out=E('case-value');if(!out)return;out.textContent=weight!=null&&weight>0&&price!=null?cash(weight/GRAMS_PER_LB*price):price!=null?'Enter board weight to calculate':'Enter a board-grade price';var basis=E('case-basis');if(basis)basis.textContent=weight!=null&&weight>0&&price!=null?weight+' g ÷ '+GRAMS_PER_LB+' g/lb × '+cash(price)+'/lb • '+(E('case-price').dataset.edited==='yes'?'entered price':E('case-price').dataset.origin||'entered price'):price!=null?cash(price)+'/lb • '+(E('case-price').dataset.origin||'planning estimate')+'. Add the scale weight for this board.':'No whole-board estimate until a board-grade price is available.';try{window.dispatchEvent(new CustomEvent('boardSensePlanningUpdated',{detail:{weightGrams:weight!=null&&weight>0?weight:null,gradeId:E('case-category').value}}))}catch(_){}}
async function loadMarket(){try{var r=await fetch(API+'/market-intelligence',{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);market=await r.json()}catch(_){market={status:'unavailable',metals:{}}}if(active&&E('case-market'))E('case-market').innerHTML=marketHTML(active.combined||{})}
function render(p){var box=ensure();if(!box)return;active=p;var d=p.combined||{},views=photoViews(p),items=views.reduce(function(all,v){return all.concat(v.blueprint.component_index||[])},[]),subtype=((d.three_answers||{}).identity||{}).subtype||((d.equipment_subtype||{}).subtype)||'',boardId=gradeId(d.grade,(d.board_type||'')+' '+subtype),quote=boardId&&quoteFor(boardId),reference=buyerReference(boardId),price=quote!=null?quote:reference?reference.price:null,econ=d.recovery_economics||{},paths=econ.paths||{},pathRows=Array.isArray(paths)?paths:Object.keys(paths).map(function(k){return paths[k]});var title=d.board_type||'Board identity under review';
var image=views.length?views.map(function(v){return '<div class="case-card"><b>'+esc(v.label)+' • '+(v.blueprint.component_index||[]).length+' numbered regions</b><br><img class="case-photo" src="'+esc(API+v.blueprint.image_url)+'" alt="'+esc(v.label)+' with numbered detected regions"></div>'}).join(''):'<div class="case-card">No safe numbered blueprint available for these photos.</div>';
box.hidden=false;box.innerHTML='<div class="case-head"><div><div class="case-kicker">SCRAP RADAR FAMILY • BOARD SENSE CASE</div><h2>'+esc(title)+'</h2><span>Grade '+esc(d.grade||'unresolved')+' • Identity '+esc(d.confidence==null?'unavailable':d.confidence+'%')+' • Recovery score '+esc(d.score==null?'unavailable':d.score)+'</span></div><button type="button" id="case-print">Print / Save PDF</button></div>'+
'<div class="case-grid"><div class="case-card"><b>Board identity</b><br>'+esc(title)+'<br>Same-board check: '+esc((d.same_board_verification||{}).status||'not supplied')+'<br>Condition: '+esc((d.condition_and_harvest||{}).condition||'not assessed')+'</div><div class="case-card"><b>What the photo shows</b><br>'+items.length+' numbered detector regions across the shown views<br>'+esc((d.recovery_signals||[]).slice(0,5).join(' • ')||'No recovery signals supplied')+'</div><div class="case-card"><b>Suggested buyer category</b><br>'+esc(boardId||'Choose a category below')+'<br>Confirm or correct it in the value worksheet.</div></div>'+
'<h3>Numbered board map</h3><p class="case-note">Each photo is a view of the same board. Markers are local to their photo; repeated parts are not counted twice for value.</p><div class="case-grid">'+image+'</div><div class="case-index">'+views.map(function(v){return (v.blueprint.component_index||[]).map(function(x){return '<div class="case-index-item"><span class="case-number">'+esc(x.number)+'</span><b>'+esc(v.label)+': '+esc(x.label)+'</b><br><span class="case-note">'+(x.confidence!=null?'Detector '+esc(x.confidence)+'% • ':'')+esc(x.context_guard||x.geometry_guard||'Visible component candidate; composition not assayed.')+'</span></div>'}).join('')}).join('')+'</div>'+
'<h3>Whole-board value worksheet</h3><p class="case-note"><b>Estimated value — not an exact price.</b> Buyer payout depends on grade, weight, condition, location and the quote available at sale.</p><div class="case-grid"><div class="case-card"><label>Buyer board category<select id="case-category"><option value="">Choose buyer category</option>'+CATEGORIES.map(function(x){return '<option value="'+esc(x[0])+'"'+(x[0]===boardId?' selected':'')+'>'+esc(x[1])+'</option>'}).join('')+'</select></label><span class="case-note">Confirm the buyer grade; SPIKE identity and buyer categories can differ.</span><label>Board weight (grams)<input id="case-weight" type="number" min="0" step="any" inputmode="decimal" placeholder="Enter scale weight"></label><span class="case-note">Weight may be added after the photo scan.</span></div><div class="case-card"><label><span id="case-price-label">Buyer price for '+esc(boardId||'selected board')+' ($/lb)</span><input id="case-price" type="number" min="0" step="any" inputmode="decimal" placeholder="Enter a price" value="'+(price==null?'':price)+'"></label><span class="case-note" id="case-price-note">'+priceNote(boardId)+'</span></div><div class="case-card"><b>Estimated gross sale whole — not an exact price</b><br><span class="case-total" id="case-value"></span><br><span class="case-note" id="case-basis"></span></div></div>'+
'<h3>Selective and deeper recovery</h3><div class="case-grid">'+(['SELL WHOLE','SELECTIVE HARVEST','DEEPER RECOVERY'].map(function(name){var x=pathRows.find(function(row){return row&&String(row.path||'').toUpperCase()===name});return '<div class="case-card"><b>'+name+' • ESTIMATED VALUE</b><br>'+(x&&x.status!=='needs_value'&&x.net_value!=null?'Entered-value comparison: '+cash(x.net_value):'No measured yield / buyer offer entered')+'<br><span class="case-note">'+(name==='SELL WHOLE'?'Board weight × board-grade buyer price.':name==='SELECTIVE HARVEST'?'Parts payout + remaining board payout − costs.':'Recovered payout + residual payout − costs; assay and refiner terms matter.')+'</span></div>'}).join(''))+'</div>'+
'<h3>Scrap Radar metal market context</h3><div id="case-market">Loading market data…</div><p class="case-note">This is a working board report. Detector markers identify areas to inspect. Quotes and measured weights support dollar totals; the recovery score is not a dollar amount. Print while this case is open; uploaded photos are not saved in this browser report.</p>';
var input=E('case-price');input.dataset.origin=quote!=null?'saved local buyer quote':reference?'dated U.S. buyer-sample planning estimate':'entered price';E('case-category').addEventListener('change',refreshCategory);['case-weight','case-price'].forEach(function(id){E(id).addEventListener('input',function(){if(id==='case-price')this.dataset.edited='yes';refreshTotals()})});E('case-print').onclick=function(){window.print()};refreshTotals();loadMarket()}
window.addEventListener('boardSenseCaseReport',function(ev){if(ev.detail&&ev.detail.blocked){active=null;var b=E('boardCaseReport');if(b)b.hidden=true;return}if(ev.detail&&ev.detail.payload)render(ev.detail.payload)});
window.addEventListener('boardSenseCaseReportReset',function(){active=null;var b=E('boardCaseReport');if(b)b.hidden=true});
})();
