/* Scrap Radar Source Finder v0.2 */
(function(){
'use strict';

const TARGET_KEY='scrapRadarInspectionTargetV1';
const SOURCES=[
 {id:'hard-drive',icon:'💽',name:'Hard drive',summary:'Permanent magnets and precision electronics can justify a closer look.',materials:[['Neodymium','strong'],['Praseodymium','possible'],['Dysprosium','possible']],note:'Magnet family, markings or assay are stronger evidence than appearance.',locator:{target:'Actuator magnet assembly',where:'Inside the drive beside and partly over/under the read-write actuator arm and voice-coil area.',look:'Usually one or two curved or flat metal-backed magnetic plates near the pivoting arm. The shiny platter is not the rare-earth target.',preserve:'Keep the magnet/backing assembly intact and sorted by drive type until you know whether reuse or a magnet buyer beats raw recovery.',watch:'Strong magnets can pinch fingers and loose drive parts can have sharp edges. Do not use appearance alone to assign rare-earth mass.'}},
 {id:'speaker',icon:'🔊',name:'Speaker / audio magnet',summary:'Permanent-magnet assemblies may contain rare-earth magnet material.',materials:[['Neodymium','strong'],['Praseodymium','possible'],['Dysprosium','possible'],['Samarium','possible']],note:'Older and lower-cost speakers may use ferrite instead of rare-earth magnets.',locator:{target:'Rear magnet / motor assembly',where:'At the back of the speaker basket, directly behind the voice coil and cone.',look:'A compact ring, puck or stacked magnet assembly. Small high-output speakers may use neodymium; large dark ceramic rings are often ferrite.',preserve:'Keep the complete magnet/motor assembly intact when practical, especially if the speaker or magnet may have reuse value.',watch:'Do not call a speaker magnet rare earth from size or color alone. Confirm magnet family or part information.'}},
 {id:'motor',icon:'⚙️',name:'Motor / generator',summary:'High-performance permanent-magnet motors are worth separating from ordinary motor scrap.',materials:[['Neodymium','strong'],['Praseodymium','possible'],['Dysprosium','possible'],['Terbium','possible']],note:'Do not assume every motor contains rare-earth magnets. Motor type and magnet identification matter.',locator:{target:'Permanent-magnet rotor area',where:'In permanent-magnet motors, inspect the rotor or rotor-adjacent magnet carrier. Ordinary induction motors may have no rare-earth magnets at all.',look:'Segmented or buried magnet pieces arranged around a rotor are common in BLDC/PMSM designs.',preserve:'Record the motor model/type first. Preserve an intact rotor or identified magnet section until its design is confirmed.',watch:'Motors can contain heavy rotating parts and strong magnetic forces. Do not dismantle energized equipment.'}},
 {id:'nimh',icon:'🔋',name:'NiMH battery pack',summary:'Known NiMH streams can carry several rare-earth and battery materials.',materials:[['Lanthanum','strong'],['Nickel','strong'],['Cerium','possible'],['Neodymium','possible'],['Praseodymium','possible'],['Cobalt','possible']],note:'Keep intact packs in a qualified battery-recycling path and confirm chemistry from labeling or documentation.',locator:{target:'Pack label / chemistry identification',where:'Start on the outside case, manufacturer label, vehicle/device documentation and pack part number.',look:'Look for NiMH or nickel-metal hydride chemistry identification, not loose internal material.',preserve:'Keep the battery pack intact, protected from terminals shorting, and routed as a documented NiMH stream.',watch:'Do not open, crush or separate cells in Scrap Radar. Damaged battery packs require qualified handling.'}},
 {id:'li-ion',icon:'🔋',name:'Lithium-ion battery',summary:'The chemistry label matters because cathode composition varies widely.',materials:[['Lithium','strong'],['Graphite','strong'],['Nickel','possible'],['Cobalt','possible']],note:'Do not open, crush or process damaged cells in Scrap Radar. Use a qualified battery recycler.',locator:{target:'Chemistry label / pack identity',where:'Inspect the external pack label, cell markings, device documentation and manufacturer part number.',look:'Look for Li-ion/Li-poly identification and, when documented, the specific cathode chemistry or pack family.',preserve:'Keep cells/packs intact, terminals protected and separated for a qualified battery recycler.',watch:'Swollen, hot, punctured or damaged lithium batteries are a fire risk. Do not open or mechanically process them.'}},
 {id:'display',icon:'🖥️',name:'Display / touchscreen / lamp phosphor',summary:'Thin coatings and phosphors can contain critical materials even when recoverable mass is tiny.',materials:[['Indium','strong'],['Yttrium','possible'],['Europium','possible'],['Terbium','possible'],['Gallium','possible']],note:'Screen area or lamp size is not a measurement of contained material.',locator:{target:'Display stack / coating-bearing layer',where:'The relevant material may be in transparent conductive coatings, phosphor layers, LEDs or backlight components rather than a visible chunk of metal.',look:'Usually nothing visually distinctive proves indium or phosphor chemistry. Panel/model documentation matters.',preserve:'Keep identified panels or lamp/display streams whole and labeled until a downstream specialist confirms acceptance.',watch:'Do not break screens or lamps simply to chase trace material. Thin-film presence does not mean profitable recoverable mass.'}},
 {id:'semiconductor',icon:'💻',name:'RF / power / semiconductor electronics',summary:'Specific device families can contain high-value critical materials in very small masses.',materials:[['Gallium','strong'],['Germanium','possible'],['Tantalum','possible'],['Tungsten','possible'],['Indium','possible']],note:'Part numbers, package type and device documentation are better evidence than board appearance.',locator:{target:'Marked RF / power semiconductor packages',where:'Inspect RF sections, power stages, telecom modules, high-frequency amplifiers and clearly marked semiconductor packages.',look:'Part numbers, logos and package families are more useful than color. GaN/GaAs parts should be supported by device documentation.',preserve:'Photograph markings before removal. Keep unusual or high-value modules intact until component identity is verified.',watch:'Do not assign whole-board gallium/germanium value because one semiconductor family may use it in tiny quantities.'}},
 {id:'capacitors',icon:'🧩',name:'Capacitor-rich electronics',summary:'Some sorted capacitor families may justify component-level separation.',materials:[['Tantalum','strong'],['Nickel','possible']],note:'Tantalum should be supported by component family, markings or testing before value is assigned.',locator:{target:'Identifiable tantalum capacitor families',where:'Look around dense logic, telecom and power-conditioning areas for capacitor packages with recognizable family/markings.',look:'Package style and markings matter. Color alone is not reliable enough to call a capacitor tantalum.',preserve:'Photograph and sort only components that have a defensible family identification; otherwise leave them with the board value.',watch:'Selective harvest only makes sense when recovered value beats time and loss of whole-board value.'}},
 {id:'carbide',icon:'🛠️',name:'Carbide tooling / dense tool scrap',summary:'Tooling streams can be much more valuable when separated from ordinary steel.',materials:[['Tungsten','strong'],['Cobalt','strong']],note:'Tool grade, density, markings or XRF can help distinguish tungsten-carbide streams.',locator:{target:'Cutting insert / carbide working end',where:'Inspect replaceable cutting inserts, brazed tips, drill/mill working ends and dense wear parts.',look:'Carbide is often unusually dense for its size and may carry grade/manufacturer markings.',preserve:'Keep carbide pieces separate from steel shanks and mixed ferrous scrap when identity is supported.',watch:'Chipped tooling can have razor-sharp edges. Density is a clue, not a complete alloy identification.'}},
 {id:'solar',icon:'☀️',name:'Solar / photovoltaic material',summary:'PV chemistry varies by technology, so panel type matters before any material value is assumed.',materials:[['Tellurium','possible'],['Indium','possible'],['Gallium','possible'],['Germanium','possible']],note:'Use manufacturer or module chemistry information where available. A generic solar panel does not prove these materials.',locator:{target:'Module nameplate / known cell technology',where:'Start with the rear label, manufacturer/model and documented PV technology before considering the cell layers.',look:'CdTe, CIGS and other technologies are identified by documentation, not by the panel looking different to the eye.',preserve:'Keep panels or sorted technology-specific streams intact for an appropriate solar recycler.',watch:'Do not break modules to search for trace critical materials. Glass, electrical damage and unknown chemistry add risk and cost.'}},
 {id:'optics',icon:'🔬',name:'Fiber optics / lasers / specialty glass',summary:'Specialty optical components may contain rare-earth dopants or semiconductor materials.',materials:[['Erbium','strong'],['Ytterbium','possible'],['Germanium','possible'],['Yttrium','possible'],['Holmium','possible'],['Thulium','possible']],note:'Optical-component identity or documentation is normally needed because concentrations can be very low.',locator:{target:'Marked optical / laser module',where:'Look for labeled fiber amplifiers, laser modules, specialty optical assemblies and documented doped-fiber components.',look:'Model numbers and optical specifications are the useful clues; the dopant itself is generally not visible.',preserve:'Keep specialty optical modules intact and record labels before any downstream handoff.',watch:'Do not operate unknown laser equipment. Trace dopants can be valuable in industry without being recoverable from one small component.'}},
 {id:'alloy',icon:'🔩',name:'Specialty alloy / solder stream',summary:'Sorted alloys and solders can contain critical metals that disappear inside a mixed-metal pile.',materials:[['Nickel','strong'],['Antimony','possible'],['Bismuth','possible'],['Cobalt','possible'],['Scandium','possible']],note:'Alloy certification, markings or XRF are the best path to a defensible value.',locator:{target:'Marked alloy / known solder stream',where:'Start with alloy stamps, manufacturer specs, controlled process scrap or XRF-sortable pieces rather than random mixed metal.',look:'Appearance overlaps heavily between alloys. Markings, density and XRF are much stronger evidence.',preserve:'Keep known alloy families and production/offcut streams segregated so their chemistry is not diluted into mixed scrap.',watch:'Never infer a premium alloy from color alone. A clean sorted stream is often worth more than a guessed composition.'}}
];

function el(id){return document.getElementById(id)}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function selectedSource(){return SOURCES.find(x=>x.id===el('cm-source-select')?.value)||null}
function confidenceLabel(level){return level==='strong'?'STRONG CANDIDATE':'POSSIBLE CANDIDATE'}
function setMaterial(name){const select=el('cm-material');if(!select)return;select.value=name;select.dispatchEvent(new Event('change',{bubbles:true}));el('cm-evidence')?.scrollIntoView({behavior:'smooth',block:'center'})}
function saveTarget(src){
 if(!src||!src.locator)return;
 const packet={version:1,createdAt:new Date().toISOString(),sourceId:src.id,sourceName:src.name,target:src.locator.target,where:src.locator.where,look:src.locator.look,preserve:src.locator.preserve,watch:src.locator.watch,materials:src.materials.map(x=>({name:x[0],candidate:x[1]})),rule:'Inspection target only. This does not prove composition, recoverable mass or cash value.'};
 try{localStorage.setItem(TARGET_KEY,JSON.stringify(packet));const s=el('cm-target-status');if(s)s.textContent='✓ Inspection target saved for Board Sense / SPIKE.'}catch(_){const s=el('cm-target-status');if(s)s.textContent='Could not save inspection target on this device.'}
}
function locatorHtml(src){const x=src.locator;if(!x)return '';return '<div class="cm-locator"><div class="cm-locator-head"><div><span>COMPONENT LOCATION</span><h4>📍 LOOK HERE: '+esc(x.target)+'</h4></div><button type="button" class="cm-target-btn" data-save-target>Save as SPIKE target</button></div><div class="cm-locator-grid"><div><b>WHERE TO LOOK</b><p>'+esc(x.where)+'</p></div><div><b>WHAT IT LOOKS LIKE</b><p>'+esc(x.look)+'</p></div><div><b>WHAT TO PRESERVE</b><p>'+esc(x.preserve)+'</p></div><div class="watch"><b>WATCH OUT</b><p>'+esc(x.watch)+'</p></div></div><small id="cm-target-status" class="cm-target-status">This target can be handed to Board Sense later without claiming the material is proven.</small></div>'}
function render(){
 const src=selectedSource(),host=el('cm-source-results');if(!host)return;
 if(!src){host.innerHTML='<div class="cm-source-empty"><b>Choose a source item.</b><span>Scrap Radar will show materials worth checking, where to inspect, and the evidence needed before value is assigned.</span></div>';return}
 host.innerHTML='<div class="cm-source-summary"><span class="cm-source-big-icon" aria-hidden="true">'+src.icon+'</span><div><h4>'+esc(src.name)+'</h4><p>'+esc(src.summary)+'</p></div></div>'+locatorHtml(src)+'<div class="cm-source-candidates">'+src.materials.map(([name,level])=>'<button type="button" class="cm-source-material '+level+'" data-cm-source-material="'+esc(name)+'"><span><b>'+esc(name)+'</b><small>'+confidenceLabel(level)+'</small></span><span class="cm-source-arrow">Use →</span></button>').join('')+'</div><div class="cm-source-note"><b>Evidence checkpoint</b><span>'+esc(src.note)+'</span></div><p class="cm-source-disclaimer">Source matching and component location are inspection guides, not proof of composition or recoverable mass. Confirm identity, supported quantity and a real downstream buyer before assigning cash-out value.</p>';
 host.querySelectorAll('[data-cm-source-material]').forEach(b=>b.addEventListener('click',()=>setMaterial(b.getAttribute('data-cm-source-material'))));
 host.querySelector('[data-save-target]')?.addEventListener('click',()=>saveTarget(src));
}
function install(){
 const section=el('critical-materials');if(!section||el('cm-source-finder'))return false;
 const truth=section.querySelector('.cm-truth-grid');if(!truth)return false;
 const box=document.createElement('div');box.id='cm-source-finder';box.className='cm-source-finder';
 box.innerHTML='<div class="cm-source-head"><div><span class="cm-source-kicker">FIELD SOURCE FINDER</span><h3>🔎 What are you holding?</h3><p>Start with the object or scrap stream, then work backward to the critical materials worth checking.</p></div><label>Source item<select id="cm-source-select"><option value="">Choose a source item…</option>'+SOURCES.map(x=>'<option value="'+esc(x.id)+'">'+esc(x.name)+'</option>').join('')+'</select></label></div><div id="cm-source-results"></div>';
 truth.insertAdjacentElement('afterend',box);
 el('cm-source-select').addEventListener('change',render);render();return true;
}
function loadCss(){if(document.querySelector('link[data-sr-source-finder-css]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='scrap_radar_source_finder.css?v=2';l.setAttribute('data-sr-source-finder-css','1');document.head.appendChild(l)}
function start(){loadCss();let tries=0;const go=()=>{tries++;if(install()||tries>100)return;setTimeout(go,100)};go()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
