/* Scrap Radar Critical Materials Intelligence v0.1 */
(function(){
'use strict';
const MATERIALS=[
 {group:'Rare Earth Elements',name:'Neodymium',symbol:'Nd',sources:'NdFeB permanent magnets in hard drives, speakers, motors and generators',evidence:'Magnet type, part markings or assay/XRF; presence in a magnet does not prove recoverable quantity',route:'Magnet reuse, specialist magnet recycler or qualified refiner'},
 {group:'Rare Earth Elements',name:'Praseodymium',symbol:'Pr',sources:'High-performance NdFeB magnets, specialty alloys and glass',evidence:'Usually alloy-context or assay evidence; visual appearance alone is insufficient',route:'Specialist magnet/alloy recycler or refiner'},
 {group:'Rare Earth Elements',name:'Dysprosium',symbol:'Dy',sources:'Some high-temperature NdFeB magnets and specialty alloys',evidence:'Requires composition data or assay; cannot be inferred from an ordinary magnet photo',route:'Specialist magnet recycler/refiner'},
 {group:'Rare Earth Elements',name:'Terbium',symbol:'Tb',sources:'Specialty magnets, phosphors and optical/electronic materials',evidence:'Component documentation or assay normally required',route:'Specialty electronics/phosphor or rare-earth refiner'},
 {group:'Rare Earth Elements',name:'Samarium',symbol:'Sm',sources:'SmCo permanent magnets and specialty alloys',evidence:'Magnet family identification plus documentation/assay',route:'Magnet reuse or specialist magnet recycler/refiner'},
 {group:'Rare Earth Elements',name:'Cerium',symbol:'Ce',sources:'Polishing compounds, catalysts, glass and some alloys',evidence:'Product chemistry, label/SDS or assay; broad product category is not enough',route:'Process-specific recycler/refiner'},
 {group:'Rare Earth Elements',name:'Lanthanum',symbol:'La',sources:'NiMH batteries, catalysts, optics and specialty alloys',evidence:'Battery chemistry/documentation or assay',route:'Qualified battery or rare-earth recycler'},
 {group:'Rare Earth Elements',name:'Yttrium',symbol:'Y',sources:'Phosphors, ceramics, LEDs, lasers and specialty electronics',evidence:'Part chemistry/documentation or assay',route:'Specialist electronics/phosphor refiner'},
 {group:'Rare Earth Elements',name:'Europium',symbol:'Eu',sources:'Display and lamp phosphors',evidence:'Known phosphor stream or assay; not visually quantifiable',route:'Specialist phosphor/e-waste refiner'},
 {group:'Rare Earth Elements',name:'Gadolinium',symbol:'Gd',sources:'Specialty magnets, electronics and optical materials',evidence:'Documentation or assay',route:'Specialty recycler/refiner'},
 {group:'Rare Earth Elements',name:'Erbium',symbol:'Er',sources:'Fiber-optic and laser materials, specialty glass',evidence:'Known optical component chemistry or assay',route:'Specialty optical/electronics refiner'},
 {group:'Rare Earth Elements',name:'Scandium',symbol:'Sc',sources:'Specialty aluminum alloys, lighting and advanced materials',evidence:'Alloy certification or assay',route:'Specialty alloy recycler/refiner'},
 {group:'Rare Earth Elements',name:'Holmium',symbol:'Ho',sources:'Specialty magnets, lasers and optical materials',evidence:'Documentation or assay',route:'Specialty refiner'},
 {group:'Rare Earth Elements',name:'Thulium',symbol:'Tm',sources:'Specialty lasers and medical/optical materials',evidence:'Documentation or assay',route:'Specialty refiner'},
 {group:'Rare Earth Elements',name:'Ytterbium',symbol:'Yb',sources:'Fiber lasers and specialty alloys',evidence:'Documentation or assay',route:'Specialty optical/alloy refiner'},
 {group:'Rare Earth Elements',name:'Lutetium',symbol:'Lu',sources:'Specialty scintillators, catalysts and research/medical materials',evidence:'Known component chemistry or assay',route:'Specialty refiner'},
 {group:'Rare Earth Elements',name:'Promethium',symbol:'Pm',sources:'Specialized radioactive applications, not an ordinary scrap target',evidence:'Do not infer from consumer scrap; regulated identification is required',route:'Regulated radioactive-material pathway only'},
 {group:'Critical Battery / Energy Materials',name:'Lithium',symbol:'Li',sources:'Lithium-ion batteries and some specialty glass/ceramics',evidence:'Battery chemistry label, pack documentation or qualified testing',route:'Qualified battery recycler; do not treat damaged cells as loose-metal scrap'},
 {group:'Critical Battery / Energy Materials',name:'Cobalt',symbol:'Co',sources:'Some lithium-ion cathodes, superalloys and hard metals',evidence:'Battery chemistry/alloy identification or assay',route:'Qualified battery or alloy recycler/refiner'},
 {group:'Critical Battery / Energy Materials',name:'Nickel',symbol:'Ni',sources:'Stainless/superalloys, NiMH batteries and some lithium-ion cathodes',evidence:'Known alloy/battery chemistry or assay',route:'Alloy yard, battery recycler or refiner depending on form'},
 {group:'Critical Electronics Materials',name:'Gallium',symbol:'Ga',sources:'GaAs/GaN semiconductors, LEDs, RF and power electronics',evidence:'Known device/semiconductor type or assay; board presence alone is not proof',route:'Specialist semiconductor/e-waste refiner'},
 {group:'Critical Electronics Materials',name:'Germanium',symbol:'Ge',sources:'Fiber optics, infrared optics and specialty semiconductors',evidence:'Known optical/semiconductor component or assay',route:'Specialty optical/electronics refiner'},
 {group:'Critical Electronics Materials',name:'Indium',symbol:'In',sources:'ITO coatings in displays/touchscreens and some solders/semiconductors',evidence:'Known display coating/chemistry or assay; screen area does not equal recoverable mass',route:'Display/electronics specialist refiner'},
 {group:'Critical Electronics Materials',name:'Tantalum',symbol:'Ta',sources:'Tantalum capacitors and specialty alloys',evidence:'Component family/marking plus confirmation where needed',route:'Sorted component buyer or specialty refiner'},
 {group:'Critical Electronics Materials',name:'Tungsten',symbol:'W',sources:'Carbide tooling, vibration weights, contacts and specialty electronics',evidence:'Density/tool grade, markings or assay',route:'Carbide buyer, alloy recycler or refiner'},
 {group:'Critical Electronics Materials',name:'Tellurium',symbol:'Te',sources:'Some solar cells, thermoelectrics and specialty alloys',evidence:'Known module/material chemistry or assay',route:'Solar/specialty-material refiner'},
 {group:'Critical Electronics Materials',name:'Antimony',symbol:'Sb',sources:'Lead alloys, flame retardant systems and some semiconductors',evidence:'Known alloy/product chemistry or assay',route:'Lead/alloy recycler or specialty refiner'},
 {group:'Critical Electronics Materials',name:'Bismuth',symbol:'Bi',sources:'Low-melt alloys, lead-free solders and specialty components',evidence:'Known alloy/solder chemistry or assay',route:'Specialty alloy/refiner'},
 {group:'Critical Electronics Materials',name:'Graphite',symbol:'C',sources:'Lithium-ion battery anodes and industrial carbon products',evidence:'Known battery/process stream; black powder appearance alone is not proof of grade',route:'Qualified battery/material recycler'}
];
function el(id){return document.getElementById(id)}
function money(v){return '$'+Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function selected(){const n=el('cm-material');return MATERIALS.find(x=>x.name===(n&&n.value))||null}
function renderCatalog(filter){const host=el('cm-catalog');if(!host)return;const q=(filter||'').trim().toLowerCase();const rows=MATERIALS.filter(x=>!q||[x.name,x.symbol,x.group,x.sources].join(' ').toLowerCase().includes(q));el('cm-count').textContent=rows.length+' materials';let groups={};rows.forEach(x=>(groups[x.group]||(groups[x.group]=[])).push(x));host.innerHTML=Object.keys(groups).map(g=>'<div class="cm-group"><h3>'+esc(g)+' <span>'+groups[g].length+'</span></h3>'+groups[g].map(x=>'<button type="button" class="cm-row" data-cm="'+esc(x.name)+'"><span><b>'+esc(x.name)+'</b> <small>'+esc(x.symbol)+'</small></span><span>'+esc(x.sources)+'</span></button>').join('')+'</div>').join('')||'<p class="cm-empty">No matching critical material.</p>';host.querySelectorAll('[data-cm]').forEach(b=>b.onclick=()=>{el('cm-material').value=b.getAttribute('data-cm');renderCase()})}
function renderCase(){const m=selected(),box=el('cm-evidence');if(!box)return;if(!m){box.innerHTML='<b>Choose a material.</b><span>Scrap Radar will show likely source streams, evidence requirements and realistic downstream path.</span>';calculate();return}box.innerHTML='<div><b>'+esc(m.name)+' ('+esc(m.symbol)+')</b><span>'+esc(m.group)+'</span></div><div><b>Where it may occur</b><span>'+esc(m.sources)+'</span></div><div><b>Evidence needed</b><span>'+esc(m.evidence)+'</span></div><div><b>Likely downstream path</b><span>'+esc(m.route)+'</span></div>';calculate()}
function calculate(){const grams=Math.max(0,Number(el('cm-grams')?.value)||0),bench=Math.max(0,Number(el('cm-benchmark')?.value)||0),quote=Math.max(0,Number(el('cm-buyer-quote')?.value)||0);const theoretical=grams*bench,cash=grams*quote;el('cm-theoretical').textContent=money(theoretical);el('cm-cash').textContent=quote>0?money(cash):'NO BUYER QUOTE';let status='EVIDENCE FIRST';let detail='Presence in a product is not proof of recoverable quantity. Enter mass only when supported by measurement, documentation or assay.';if(grams>0&&bench>0){status='THEORETICAL VALUE ONLY';detail='Benchmark × supported material mass is a reference value, not a payout.'}if(grams>0&&quote>0){status='CASH-OUT BASIS ENTERED';detail='Buyer/refiner quote × supported mass is the current cash-out estimate. Confirm minimum lots, fees, assay terms and settlement basis.'}el('cm-status').textContent=status;el('cm-status-detail').textContent=detail}
function install(){if(el('critical-materials'))return;const pricebook=el('pricebook');if(!pricebook)return;const section=document.createElement('section');section.id='critical-materials';section.className='sr-panel cm-panel';section.innerHTML='<div class="cm-head"><div><h2>🧪 Rare Earth + Critical Materials</h2><p class="panel-kicker">Evidence first. A material being present is not the same as having a recoverable or sellable quantity.</p></div><span class="cm-badge">FRAMEWORK v0.1</span></div><div class="cm-truth-grid"><div><b>1. PRESENCE</b><span>What material may be present, and where?</span></div><div><b>2. RECOVERABILITY</b><span>Is there a supported quantity and practical recovery stream?</span></div><div><b>3. CASH-OUT</b><span>Is there a real buyer/refiner quote for this form and lot?</span></div></div><div class="cm-case"><h3>Critical Material Value Check</h3><div class="cm-input-grid"><label>Material<select id="cm-material"><option value="">Choose a material…</option>'+MATERIALS.map(x=>'<option>'+esc(x.name)+'</option>').join('')+'</select></label><label>Supported material mass (grams)<input id="cm-grams" type="number" min="0" step="any" inputmode="decimal" placeholder="0"></label><label>Benchmark $ / gram<input id="cm-benchmark" type="number" min="0" step="any" inputmode="decimal" placeholder="reference only"></label><label>Actual buyer/refiner quote $ / gram<input id="cm-buyer-quote" type="number" min="0" step="any" inputmode="decimal" placeholder="real cash-out basis"></label></div><div id="cm-evidence" class="cm-evidence"></div><div class="cm-value-grid"><div><span>Theoretical contained value</span><strong id="cm-theoretical">$0.00</strong></div><div><span>Cash-out estimate</span><strong id="cm-cash">NO BUYER QUOTE</strong></div></div><div class="eval-decision"><strong id="cm-status">EVIDENCE FIRST</strong><small id="cm-status-detail">Presence in a product is not proof of recoverable quantity.</small></div><p class="disclaimer">Scrap Radar does not infer recoverable rare-earth mass from a photo or product category. Benchmark value and cash-out value stay separate. Hazardous, radioactive and battery materials require appropriate qualified handling.</p></div><div class="cm-library"><div class="cm-toolbar"><input id="cm-search" type="search" placeholder="Search neodymium, tantalum, batteries, magnets…"><span id="cm-count"></span></div><div id="cm-catalog"></div></div>';
 pricebook.parentNode.insertBefore(section,pricebook);
 ['cm-material','cm-grams','cm-benchmark','cm-buyer-quote'].forEach(id=>{el(id).addEventListener('input',renderCase);el(id).addEventListener('change',renderCase)});el('cm-search').addEventListener('input',e=>renderCatalog(e.target.value));renderCatalog('');renderCase();
 const card=document.querySelector('.tool-card[href="#market"]');if(card&&card.parentNode&&!document.querySelector('.tool-card[href="#critical-materials"]')){const a=document.createElement('a');a.className='tool-card';a.href='#critical-materials';a.innerHTML='<span class="tool-icon">🧪</span><b>Critical Materials</b><small>Rare earths, evidence, recoverability and cash-out.</small><span class="tool-state live">LIVE</span>';card.parentNode.appendChild(a)}
}
function loadCss(){if(document.querySelector('link[data-sr-critical-css]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='scrap_radar_critical.css?v=1';l.setAttribute('data-sr-critical-css','1');document.head.appendChild(l)}
loadCss();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
