(function(){
'use strict';
const KEY='scrapRadarInventoryV1';
function el(id){return document.getElementById(id)}
function cash(x){return '$'+Number(x||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}
function get(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')||[]}catch(_){return []}}
function put(x){try{localStorage.setItem(KEY,JSON.stringify(x))}catch(_){}}
function materialOptions(){const s=el('calc-material');return s&&s.options.length>1?s.innerHTML:'<option value="">Choose a material…</option>'}
function selectedLabel(select){return select&&select.selectedIndex>=0?select.options[select.selectedIndex].text:'Unknown material'}
function yardQuotes(){try{return JSON.parse(localStorage.getItem('scrapRadarYardQuotesV1')||'{}')||{}}catch(_){return {}}}
function makeId(){return String(Date.now())+'_'+Math.random().toString(36).slice(2,8)}

function inject(){
 if(el('inventory'))return;
 const roi=el('roi');if(!roi)return;
 roi.insertAdjacentHTML('beforebegin',`<section id="inventory" class="sr-panel inventory-panel"><h2>📦 Inventory</h2><p class="panel-kicker">Save material that is still in your possession. Expected value and completed sale value stay separate.</p>
  <div class="inventory-entry"><div class="eval-field wide"><label>Material / Grade</label><select id="inv-material"><option value="">Choose a material…</option></select></div><div class="eval-field"><label>Qty / Weight</label><input id="inv-qty" type="number" min="0" step="any" inputmode="decimal" placeholder="0"></div><div class="eval-field"><label>Expected $ / unit</label><input id="inv-price" type="number" min="0" step="any" inputmode="decimal" placeholder="0.00"></div><button id="inv-add" class="mini-btn" type="button">Add to Inventory</button></div>
  <div class="inventory-actions"><button id="inv-from-load" class="mini-btn" type="button">Save Mixed Load Lines</button><button id="inv-clear-sold" class="mini-btn" type="button">Remove Sold Items</button><span id="inv-status" class="saved-yard-status">Inventory is stored on this device.</span></div>
  <div class="inventory-summary"><div><span>Items In Stock</span><strong id="inv-count">0</strong></div><div class="expected"><span>Expected Gross</span><strong id="inv-expected">$0.00</strong></div><div class="sold"><span>Recorded Sold Gross</span><strong id="inv-sold">$0.00</strong></div></div><div id="inventory-list" class="inventory-list"></div>
  <p class="disclaimer">Recorded sold gross is sale revenue, not automatically “additional profit.” ROI still requires the appropriate costs, savings or incremental-profit basis.</p></section>`);
 syncOptions();const src=el('calc-material');if(src)new MutationObserver(syncOptions).observe(src,{childList:true,subtree:true});
 el('inv-material')?.addEventListener('change',autoPrice);el('inv-add')?.addEventListener('click',addItem);el('inv-from-load')?.addEventListener('click',saveMixedLoad);el('inv-clear-sold')?.addEventListener('click',clearSold);render()
}
function syncOptions(){const s=el('inv-material');if(!s)return;const keep=s.value;s.innerHTML=materialOptions();if([...s.options].some(o=>o.value===keep))s.value=keep}
function autoPrice(){const id=el('inv-material')?.value,p=el('inv-price');if(!id||!p)return;const q=yardQuotes()[id];if(q!==undefined&&q!==null&&q!==''&&Number.isFinite(Number(q))){p.value=Number(q).toFixed(2);return}if(id===el('calc-material')?.value&&el('calc-price')?.value!=='')p.value=el('calc-price').value}
function addItem(){const s=el('inv-material'),q=Number(el('inv-qty')?.value),pv=el('inv-price')?.value,p=Number(pv);if(!s||!s.value||!Number.isFinite(q)||q<=0){status('Choose a material and enter a quantity greater than zero.');return}const items=get();items.unshift({id:makeId(),materialId:s.value,label:selectedLabel(s),qty:q,expectedPrice:pv!==''&&Number.isFinite(p)&&p>=0?p:null,status:'stock',saleTotal:null,createdAt:new Date().toISOString()});put(items);el('inv-qty').value='';status('Added to inventory.');render()}
function saveMixedLoad(){const rows=[...document.querySelectorAll('.load-line')],items=get();let added=0;rows.forEach(r=>{const s=r.querySelector('.load-material'),qv=r.querySelector('.load-qty')?.value,pv=r.querySelector('.load-price')?.value,q=Number(qv),p=Number(pv);if(!s||!s.value||qv===''||!Number.isFinite(q)||q<=0)return;items.unshift({id:makeId(),materialId:s.value,label:selectedLabel(s),qty:q,expectedPrice:pv!==''&&Number.isFinite(p)&&p>=0?p:null,status:'stock',saleTotal:null,createdAt:new Date().toISOString()});added++});if(!added){status('No complete mixed-load lines to save.');return}put(items);status('Saved '+added+' mixed-load line'+(added===1?'':'s')+' to inventory.');render()}
function clearSold(){const items=get(),kept=items.filter(x=>x.status!=='sold');put(kept);status('Removed '+(items.length-kept.length)+' sold item'+(items.length-kept.length===1?'':'s')+'.');render()}
function status(msg){const x=el('inv-status');if(x){x.textContent=msg;x.className='saved-yard-status fresh'}}
function markSold(id){const items=get(),item=items.find(x=>x.id===id);if(!item)return;const expected=item.expectedPrice===null?null:item.qty*item.expectedPrice;const raw=window.prompt('Actual total sale amount for '+item.label+'?',expected===null?'':Number(expected).toFixed(2));if(raw===null)return;const total=Number(raw);if(!Number.isFinite(total)||total<0){status('Sale amount was not saved.');return}item.status='sold';item.saleTotal=total;item.soldAt=new Date().toISOString();put(items);status('Marked '+item.label+' sold for '+cash(total)+'.');render()}
function remove(id){put(get().filter(x=>x.id!==id));render()}
function loadEvaluator(id){const item=get().find(x=>x.id===id);if(!item)return;const s=el('calc-material');if(s&&[...s.options].some(o=>o.value===item.materialId)){s.value=item.materialId;s.dispatchEvent(new Event('change',{bubbles:true}))}if(el('calc-weight')){el('calc-weight').value=item.qty;el('calc-weight').dispatchEvent(new Event('input',{bubbles:true}))}if(item.expectedPrice!==null&&el('calc-price')){el('calc-price').value=item.expectedPrice;el('calc-price').dispatchEvent(new Event('input',{bubbles:true}))}el('evaluator')?.scrollIntoView({behavior:'smooth',block:'start'})}
function render(){const root=el('inventory-list');if(!root)return;const items=get();root.innerHTML='';let stock=0,expected=0,sold=0;if(!items.length){const d=document.createElement('div');d.className='empty';d.textContent='No saved inventory yet.';root.appendChild(d)}items.forEach(item=>{if(item.status==='sold')sold+=Number(item.saleTotal||0);else{stock++;if(item.expectedPrice!==null)expected+=item.qty*item.expectedPrice}const row=document.createElement('div');row.className='inventory-row '+(item.status==='sold'?'sold':'');const name=document.createElement('div');name.className='inv-name';name.textContent=item.label;const meta=document.createElement('div');meta.className='inv-meta';meta.textContent='Added '+new Date(item.createdAt).toLocaleString();name.appendChild(meta);const qty=document.createElement('div');qty.textContent=String(item.qty);const value=document.createElement('div');value.className='inv-value';value.textContent=item.status==='sold'?cash(item.saleTotal):item.expectedPrice===null?'No price':cash(item.qty*item.expectedPrice);const state=document.createElement('div');state.className='inv-status';state.textContent=item.status==='sold'?'SOLD'+(item.soldAt?' • '+new Date(item.soldAt).toLocaleDateString():''):'IN STOCK'+(item.expectedPrice===null?' • price needed':' • expected');const actions=document.createElement('div');actions.className='row-actions';if(item.status!=='sold'){const load=document.createElement('button');load.className='tiny-btn';load.type='button';load.textContent='Evaluate';load.addEventListener('click',()=>loadEvaluator(item.id));const sale=document.createElement('button');sale.className='tiny-btn';sale.type='button';sale.textContent='Sold';sale.addEventListener('click',()=>markSold(item.id));actions.append(load,sale)}const del=document.createElement('button');del.className='tiny-btn danger';del.type='button';del.textContent='Delete';del.addEventListener('click',()=>remove(item.id));actions.appendChild(del);row.append(name,qty,value,state,actions);root.appendChild(row)});if(el('inv-count'))el('inv-count').textContent=String(stock);if(el('inv-expected'))el('inv-expected').textContent=cash(expected);if(el('inv-sold'))el('inv-sold').textContent=cash(sold)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject);else inject();
})();
