(function(){
'use strict';
const ROI_KEY='scrapRadarRoiLedgerV1',HISTORY_KEY='scrapRadarEvaluatorHistoryV1';
let lineId=0;
function el(id){return document.getElementById(id)}
function n(id){const x=el(id);if(!x||x.value==='')return null;const v=Number(x.value);return Number.isFinite(v)?v:null}
function v(id){return el(id)?.value??''}
function cash(x){return '$'+Number(x||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}
function text(id,x){if(el(id))el(id).textContent=x}
function getJson(k,f){try{return JSON.parse(localStorage.getItem(k)||'')||f}catch(_){return f}}
function putJson(k,x){try{localStorage.setItem(k,JSON.stringify(x))}catch(_){}}
function options(){const s=el('calc-material');return s&&s.options.length>1?s.innerHTML:'<option value="">Choose material…</option>'}
function syncLoadSelects(){document.querySelectorAll('.load-material').forEach(s=>{const keep=s.value;s.innerHTML=options();if([...s.options].some(o=>o.value===keep))s.value=keep})}
function addLine(){const root=el('load-lines');if(!root)return;const row=document.createElement('div');row.className='load-line';row.dataset.line=++lineId;row.innerHTML='<select class="load-material" aria-label="Load material">'+options()+'</select><input class="load-qty" type="number" min="0" step="any" inputmode="decimal" placeholder="0"><input class="load-price" type="number" min="0" step="any" inputmode="decimal" placeholder="0.00"><div class="line-value">$0.00</div><button class="remove-line" type="button" aria-label="Remove line">×</button>';root.appendChild(row);row.querySelectorAll('select,input').forEach(x=>{x.addEventListener('input',calcLoad);x.addEventListener('change',()=>{fillLinePrice(row);calcLoad()})});row.querySelector('.remove-line').addEventListener('click',()=>{row.remove();if(!root.children.length)addLine();calcLoad()});calcLoad()}
function fillLinePrice(row){const s=row.querySelector('.load-material'),p=row.querySelector('.load-price');if(!s||!p||p.value!=='')return;const q=getJson('scrapRadarYardQuotesV1',{})[s.value];if(q!==undefined&&q!==null&&q!==''&&Number.isFinite(Number(q)))p.value=Number(q).toFixed(2);else if(s.value===v('calc-material')&&v('calc-price')!=='')p.value=v('calc-price')}
function calcLoad(){let gross=0,qty=0,active=0;document.querySelectorAll('.load-line').forEach(r=>{const qv=r.querySelector('.load-qty').value,pv=r.querySelector('.load-price').value,q=Number(qv),p=Number(pv),ok=qv!==''&&pv!==''&&Number.isFinite(q)&&Number.isFinite(p)&&q>=0&&p>=0,value=ok?q*p:0;if(qv!==''||pv!==''||r.querySelector('.load-material').value)active++;if(qv!==''&&Number.isFinite(q))qty+=q;gross+=value;r.querySelector('.line-value').textContent=cash(value)});text('mixed-count',String(active));text('mixed-weight',Number(qty).toFixed(2));text('mixed-gross',cash(gross));text('gauge-mixed-gross',cash(gross))}
function clearLoad(){if(el('load-lines'))el('load-lines').innerHTML='';addLine()}
function calcYards(){const weight=n('yard-weight'),mpg=n('yard-mpg'),gas=n('yard-gas'),list=[];for(let i=1;i<=3;i++){const price=n('yard-price-'+i),miles=Math.max(0,n('yard-miles-'+i)||0),fees=Math.max(0,n('yard-fees-'+i)||0),name=v('yard-name-'+i).trim()||'Buyer '+i,valid=weight!==null&&weight>=0&&price!==null&&price>=0,fuel=valid&&mpg!==null&&mpg>0&&gas!==null&&gas>=0?miles*2/mpg*gas:0,net=valid?weight*price-fuel-fees:null;text('yard-net-'+i,net===null?'—':cash(net));document.querySelector('[data-yard="'+i+'"]')?.classList.remove('best');if(net!==null)list.push({i,name,net})}if(!list.length){text('yard-decision','ENTER BUYER PRICES');text('yard-detail','The best buyer is the highest net after entered fuel and fees, not automatically the highest posted price.');text('gauge-yard-net','—');return}list.sort((a,b)=>b.net-a.net);const best=list[0],second=list[1];document.querySelector('[data-yard="'+best.i+'"]')?.classList.add('best');text('gauge-yard-net',cash(best.net));text('yard-decision','✅ BEST ENTERED NET: '+best.name.toUpperCase());text('yard-detail',second?best.name+' nets '+cash(best.net)+', '+cash(best.net-second.net)+' more than the next entered buyer after fuel and fees.':best.name+' nets '+cash(best.net)+'. Add another buyer for a true comparison.')}
function copyTrip(){if(v('calc-weight')!=='')el('yard-weight').value=v('calc-weight');if(v('trip-mpg')!=='')el('yard-mpg').value=v('trip-mpg');if(v('trip-gas')!=='')el('yard-gas').value=v('trip-gas');if(v('calc-price')!==''&&!v('yard-price-1'))el('yard-price-1').value=v('calc-price');if(v('trip-miles')!==''&&!v('yard-miles-1'))el('yard-miles-1').value=v('trip-miles');if(v('trip-other')!==''&&!v('yard-fees-1'))el('yard-fees-1').value=v('trip-other');if(!v('yard-name-1'))el('yard-name-1').value='Current Buyer';calcYards();el('yard-comparison')?.scrollIntoView({behavior:'smooth',block:'start'})}
function calcRecovery(){const whole=n('br-whole'),pv=Math.max(0,n('br-partial-value')||0),pr=Math.max(0,n('br-residual')||0),pc=Math.max(0,n('br-partial-costs')||0),pm=n('br-partial-minutes'),fv=Math.max(0,n('br-full-value')||0),fr=Math.max(0,n('br-full-residual')||0),fc=Math.max(0,n('br-full-costs')||0),fm=n('br-full-minutes'),pe=['br-partial-value','br-residual','br-partial-costs'].some(id=>v(id)!==''),fe=['br-full-value','br-full-residual','br-full-costs'].some(id=>v(id)!==''),partial=pe?pv+pr-pc:null,full=fe?fv+fr-fc:null;text('br-whole-net',whole===null?'$0.00':cash(whole));text('br-partial-net',partial===null?'$0.00':cash(partial));text('br-full-net',full===null?'$0.00':cash(full));const ph=partial!==null&&pm!==null&&pm>0?(partial-(whole||0))/(pm/60):null,fh=full!==null&&fm!==null&&fm>0?(full-(whole||0))/(fm/60):null;text('br-partial-hourly',ph===null?'— / hr':cash(ph)+'/hr incremental vs whole');text('br-full-hourly',fh===null?'— / hr':cash(fh)+'/hr incremental vs whole');const paths=[];if(whole!==null)paths.push({name:'SELL WHOLE',net:whole});if(partial!==null)paths.push({name:'SELECTIVE HARVEST',net:partial});if(full!==null)paths.push({name:'DEEPER RECOVERY',net:full});if(!paths.length){text('br-decision','ENTER BOARD VALUES');text('br-detail','Use known offers, recovered values, time and costs. Do not add value just because a component looks valuable.');return}paths.sort((a,b)=>b.net-a.net);const best=paths[0];text('br-decision','📌 HIGHEST ENTERED NET: '+best.name);text('br-detail',best.name+(best.name==='SELL WHOLE'?' shows ':' currently shows ')+cash(best.net)+' net on the entered values.'+(best.name!=='SELL WHOLE'&&whole!==null?' That is '+cash(best.net-whole)+' above the whole-board offer before judging the time rate.':''))}
function roi(){return {profit:Math.max(0,n('roi-profit')||0),savings:Math.max(0,n('roi-savings')||0),recovered:Math.max(0,n('roi-recovered')||0),costs:Math.max(0,n('roi-costs')||0),potential:Math.max(0,n('roi-potential')||0),subscription:Math.max(0,n('roi-subscription')||0)}}
function loadRoi(){const d=getJson(ROI_KEY,{}),map={profit:'roi-profit',savings:'roi-savings',recovered:'roi-recovered',costs:'roi-costs',potential:'roi-potential',subscription:'roi-subscription'};Object.keys(map).forEach(k=>{if(d[k]!==undefined&&el(map[k]))el(map[k]).value=d[k]||''})}
function calcRoi(){const d=roi(),benefit=d.profit+d.savings+d.recovered,net=benefit-d.costs,after=net-d.subscription;text('roi-benefit',cash(benefit));text('roi-realized-net',cash(net));text('roi-after-sub',cash(after));text('roi-potential-show',cash(d.potential));text('gauge-roi-net',cash(net));if(benefit===0&&d.costs===0){text('roi-decision','NO REALIZED RESULTS ENTERED');text('roi-detail','Potential opportunities stay outside realized ROI until a sale, recovery or verified saving actually occurs.')}else if(d.subscription>0&&after>=0){text('roi-decision','✅ ENTERED REALIZED RESULTS COVER THE SUBSCRIPTION');text('roi-detail',cash(after)+' remains after the entered subscription/tool cost.')}else if(d.subscription>0){text('roi-decision','🟡 ENTERED REALIZED RESULTS HAVE NOT YET COVERED THE SUBSCRIPTION');text('roi-detail',cash(Math.abs(after))+' more realized net benefit would be needed to cover the entered subscription/tool cost.')}else{text('roi-decision','🟢 REALIZED ROI LEDGER ACTIVE');text('roi-detail',cash(net)+' net realized benefit is recorded. Potential opportunity remains separate at '+cash(d.potential)+'.')}putJson(ROI_KEY,d)}
function history(){return getJson(HISTORY_KEY,[])}
function renderHistory(){const root=el('roi-history');if(!root)return;const h=history();root.innerHTML='';if(!h.length){const d=document.createElement('div');d.className='empty';d.textContent='No recorded evaluator results yet.';root.appendChild(d);return}h.forEach(r=>{const row=document.createElement('div');row.className='roi-record';const a=document.createElement('span'),b=document.createElement('strong'),c=document.createElement('time');a.textContent=(r.label||'Evaluator Load')+' • evaluation only';b.textContent=cash(r.net);c.textContent=new Date(r.at).toLocaleString();row.append(a,b,c);root.appendChild(row)})}
function record(){const weight=n('calc-weight'),price=n('calc-price');if(weight===null||price===null){text('op-detail','Enter a real load result before recording it.');return}const gross=weight*price,trip=Number((el('op-costs')?.textContent||'$0').replace(/[^0-9.-]/g,''))||0,net=gross-trip,s=el('calc-material'),label=s&&s.selectedIndex>=0?s.options[s.selectedIndex].text:'Evaluator Load',h=history();h.unshift({label,gross,net,at:new Date().toISOString()});putJson(HISTORY_KEY,h.slice(0,15));renderHistory();text('op-detail','Evaluator result recorded as history only. It was NOT automatically counted as realized profit.')}
function bind(){el('add-load-line')?.addEventListener('click',addLine);el('clear-load')?.addEventListener('click',clearLoad);addLine();const src=el('calc-material');if(src)new MutationObserver(syncLoadSelects).observe(src,{childList:true,subtree:true});['yard-weight','yard-mpg','yard-gas','yard-name-1','yard-price-1','yard-miles-1','yard-fees-1','yard-name-2','yard-price-2','yard-miles-2','yard-fees-2','yard-name-3','yard-price-3','yard-miles-3','yard-fees-3'].forEach(id=>el(id)?.addEventListener('input',calcYards));el('copy-trip-to-yards')?.addEventListener('click',copyTrip);['br-whole','br-partial-value','br-residual','br-partial-minutes','br-partial-costs','br-full-value','br-full-residual','br-full-minutes','br-full-costs'].forEach(id=>el(id)?.addEventListener('input',calcRecovery));loadRoi();['roi-profit','roi-savings','roi-recovered','roi-costs','roi-potential','roi-subscription'].forEach(id=>el(id)?.addEventListener('input',calcRoi));el('record-evaluator')?.addEventListener('click',record);el('clear-roi-history')?.addEventListener('click',()=>{putJson(HISTORY_KEY,[]);renderHistory()});renderHistory();calcRoi();calcYards();calcRecovery()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();